##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hydrogzv/public_html/
    - /bin/cp -R /home/hydrogzv/build/media $DEPLOYPATH
    - /bin/cp -R /home/hydrogzv/build/static $DEPLOYPATH
    - /bin/cp /home/hydrogzv/build/asset-manifest.json $DEPLOYPATH
    - /bin/cp /home/hydrogzv/build/favicon.ico $DEPLOYPATH
    - /bin/cp /home/hydrogzv/build/index.html $DEPLOYPATH
    - /bin/cp /home/hydrogzv/build/manifest.json $DEPLOYPATH
    - /bin/cp /home/hydrogzv/build/robots.txt $DEPLOYPATH